name: "Modify dust2 config"
on:
  push:
    branches: "main"
    paths: "annotations/Dust2/*"

jobs:
  modify-config:
    runs-on: ubuntu-latest

    steps:
      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Europe/Warsaw"
      - uses: jaywcjlove/github-action-modify-file-content@main  
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          path: configs/D2.vdf
          body: "{{date:YYYY-MM-DD HH:mm:ss}} - ${{ github.event.head_commit.message }}"
          openDelimiter: "<<"
          closeDelimiter: " >>"

